# Generated by Django 4.2.7 on 2023-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/users'),
        ),
    ]
