# Generated by Django 4.2.7 on 2023-11-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_property_property_pic_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_pic',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
